### ISSUE TITLE
K8s Authentication

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/arnold#680] opened 2021-08-25 05:14 UTC
## Bug Report
While executing `bin/arnold -c eugene -e development -a hello bootstrap`
 

- `hostname -I ` does not work on Mac .
- I then replaced it with `hostname`.

**Expected behavior/code**
Deployment of Hello Application

**Actual Behavior**
Command: bootstrap

Parameters:
  K8S_DOMAIN  : AarajBhattarai
  application : hello
  customer    : eugene
  environment : development
  gpg enabled : 0
  dev mode    : 0
  log level   : info
  CLI release : 6.0.0
  image       : arnold:6.0.0
  extra volume: 

WARNING  A new Arnold release is available: 6.1.0
INFO     Consider upgrading Arnold using the 'upgrade' command
WARNING  We strongly recommend to activate the GPG mode to secure your vault passwords
Switched to context "k3d-arnold".
ERROR    Unable to authenticate to https://AarajBhattarai:52582 with the K8S_AUTH_API_KEY.

**Environment**
- Arnold version:6.0.0
- Platform: Docker version 20.10.7,docker-compose version 1.29.2,k3d version v4.4.7,
k3s version latest (default),MacOS BigSur

**Comment by jmaupetit** [comment] 2021-08-25 12:41
Hi @aarajbhattarai :wave: Thanks for the report. I'm closing this as a duplicate of #679

**Closed as completed by jmaupetit** 2021-08-25 12:41 UTC
